name: Semgrep Cloud Scan

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  semgrep:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Semgrep with Cloud Integration
        run: |
          pip install semgrep
          semgrep ci --config=auto --include='**/*.py' --exclude='.git/**'

